import type { Metadata } from "next";
import React from "react";
import { ColorProvider } from "@/context/ColorContext";
import "./_styles/globals.css";

export const metadata: Metadata = {
  title: "Niko Dola Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const primaryColor = "#88D1D4";
  const secondaryColor = "#121B41"

  return (
    <html
      lang="en"
      style={
        { "--primary-color": primaryColor, "--secondary-color": secondaryColor} as React.CSSProperties
      
      }
    >
      <body>
        <ColorProvider primaryColor={primaryColor}>
          {children}
        </ColorProvider>
      </body>
    </html>
  );
}