import type { Metadata } from "next";
import "./_styles/globals.css";

export const metadata: Metadata = {
  title: "Niko Dola Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
