import type { Metadata } from "next";
import React from "react";
import { ColorProvider } from "@/context/ColorContext";
import "./_styles/globals.css";

export const metadata: Metadata = {
  title: "Niko Dola Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const defaultColor = "#88D1D4";

  return (
    <html
      lang="en"
      style={
        { "--theme-color": defaultColor } as React.CSSProperties
      }
    >
      <body>
        <ColorProvider initialColor={defaultColor}>
          {children}
        </ColorProvider>
      </body>
    </html>
  );
}